version: '3.3'
services:
  # api:
  #   build: ./api
  #   ports:
  #    - "3000:3000"
  #   depends_on:
  #    - db
  dynamo:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - local_network
  db:
    build: ./mysql
    ports:
      - "33060:3306"
    networks:
      - local_network
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  local_network:
