service: bitcoin-api

frameworkVersion: ">=1.28.0 <2.0.0"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: sa-east-1

  environment:
    SERVICE: ${self:service}-${opt:stage, self:provider.stage}
    REGION: ${self:provider.region}
    REGISTER_USERS: register-users-${opt:stage, self:provider.stage}
    TRACK_HISTORY_DB: bitcoin-track-history-${opt:stage, self:provider.stage}
    PRIVATE_KEY: )@<_U2!Ba`xMYhFL#!r3V.,}/ySn3kPuvCZ[*f[ew+Hd5\7Kw:*G&Rq`9`-]5&;>
    BITCOIN_API_KEY: eeea17d5-d411-4d8c-85a7-989e32a1fca6
    # HOST_DB:
    # USER_DB:
    # PORT_DB:
    # PWD_DB:

  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:GetItem
      - dynamodb:Query
      - dynamodb:DeleteItem
      - dynamodb:UpdateItem
      - dynamodb:PutItem
      Resource: ['*']
    - Effect: Allow
      Action:
      - lambda:InvokeFunction
      Resource: ["*"]

functions:
  login:
    handler: src/interface/authentication.login
    events:
      - http:
          path: login
          method: GET
  sign:
    handler: src/interface/authentication.sign
    events:
      - http:
          path: sign
          method: POST
#   xChangeBitcoin:
#     handler: src/interface/bitcoin.xChangeHandler
#     events:
#       - http:
#         path: xChangeBitcoin
#         method: GET
#       - http:
#         path: xChangeBitcoin
#         method: POST
#       - http:
#         path: /
#         method: GET
#         authorizer:
#           name: authorize
#           resultTtlInSeconds: 0
#       - http:
#         path: /
#         method: POST
#         authorizer:
#           name: authorize
#           resultTtlInSeconds: 0

resources:
  Resources:
    registerUsers:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "userId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.REGISTER_USERS}
