AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/login
      Runtime: go1.x
      Events:
        login:
          Type: Api
          Properties:
            Path: /login
            Method: GET
      Environment:
        Variables:
          REGISTER_USERS: register-users-dev
          REGION: sa-east-1
          PRIVATE_KEY: )@<_U2!Ba`xMYhFL#!r3V.,}/ySn3kPuvCZ[*f[ew+Hd5\7Kw:*G&Rq`9`-]5&;>
  sign:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/sign
      Runtime: go1.x
      Events:
        sign:
          Type: Api
          Properties:
            Path: /sign
            Method: POST
      Environment:
        Variables:
          REGISTER_USERS: register-users-dev
          REGION: sa-east-1
          PRIVATE_KEY: )@<_U2!Ba`xMYhFL#!r3V.,}/ySn3kPuvCZ[*f[ew+Hd5\7Kw:*G&Rq`9`-]5&;>
  register:
    Type: AWS::Serverless::SimpleTable
    Properties:
    TableName: register-users-dev
    PrimaryKey:
      Name: userId
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

