AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  sign:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/sign
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /sign
            Method: POST
      Environment:
        Variables:
          REGISTER_USERS: register-users-dev
          REGION: sa-east-1