AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/login
      Runtime: go1.x
      Events:
        login:
          Type: Api
          Properties:
            Path: /login
            Method: GET
      Environment:
        Variables:
          REGION: sa-east-1
          PRIVATE_KEY: )@<_U2!Ba`xMYhFL#!r3V.,}/ySn3kPuvCZ[*f[ew+Hd5\7Kw:*G&Rq`9`-]5&;>
          USERS_DB: users_dev
          TRANSACTIONS_DB: transactions_dev
          BITCOIN_API_KEY: eeea17d5-d411-4d8c-85a7-989e32a1fca6
          MYSQL_HOST: bitcoin-api-docker_db_1
          MYSQL_DATABASE: db
          MYSQL_USER: gouser
          MYSQL_PASSWORD: gouser@)@<_U2
          MYSQL_PORT: "3306"
  sign:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/sign
      Runtime: go1.x
      Events:
        sign:
          Type: Api
          Properties:
            Path: /sign
            Method: POST
      Environment:
        Variables:
          REGION: sa-east-1
          PRIVATE_KEY: )@<_U2!Ba`xMYhFL#!r3V.,}/ySn3kPuvCZ[*f[ew+Hd5\7Kw:*G&Rq`9`-]5&;>
          USERS_DB: users_dev
          TRANSACTIONS_DB: transactions_dev
          BITCOIN_API_KEY: eeea17d5-d411-4d8c-85a7-989e32a1fca6
          MYSQL_HOST: bitcoin-api-docker_db_1
          MYSQL_DATABASE: db
          MYSQL_USER: gouser
          MYSQL_PASSWORD: gouser@)@<_U2
          MYSQL_PORT: "3306"
  # register:
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #   TableName: register-users-dev
  #   PrimaryKey:
  #     Name: userId
  #     Type: String
  #   ProvisionedThroughput:
  #     ReadCapacityUnits: 5
  #     WriteCapacityUnits: 5
